// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/18/2024, 2:10:41 PM
const configMerger = require("/home/Test3426547/github-bj6bef-rcqmmt/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/Test3426547/github-bj6bef-rcqmmt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/Test3426547/github-bj6bef-rcqmmt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/Test3426547/github-bj6bef-rcqmmt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/Test3426547/github-bj6bef-rcqmmt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/Test3426547/github-bj6bef-rcqmmt/plugins/**/*.{js,ts,mjs}","/home/Test3426547/github-bj6bef-rcqmmt/composables/**/*.{js,ts,mjs}","/home/Test3426547/github-bj6bef-rcqmmt/utils/**/*.{js,ts,mjs}","/home/Test3426547/github-bj6bef-rcqmmt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/Test3426547/github-bj6bef-rcqmmt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/Test3426547/github-bj6bef-rcqmmt/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["16"] = "/home/Test3426547/github-bj6bef-rcqmmt/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
