// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/18/2024, 1:59:03 PM
const configMerger = require("/home/project/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/project/plugins/**/*.{js,ts,mjs}","/home/project/composables/**/*.{js,ts,mjs}","/home/project/utils/**/*.{js,ts,mjs}","/home/project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/project/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["16"] = "/home/project/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
